version: '3.2'
services:
  node-tex:
    image: su1101/node-lualatex-haranoaji-llmk:latest
    # build: ../docker
    command: sleep infinity
    volumes:
      - type: bind
        source: ../
        target: /workspace
      - ~/.gitconfig:/root/.gitconfig
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"
