version: '3.2'
services:
  ubuntu-tex:
    image: su1101/ubuntu-node-texlive-ja
    # build: ../docker
    command: sleep infinity
    volumes:
      - type: bind
        source: ../
        target: /workspace
      - ~/.gitconfig:/root/.gitconfig
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"
